package com.brigadka.app.presentation.common.strings

object RussianStrings: Strings {
    override val tellAboutYou: String = "Расскажите о себе"
    override val tellMoreAboutYou: String = "Расскажите еще о себе"
    override val photo: String = "Фото"
    override val video: String = "Видео"
    override val videoDescription: String = "Загрузите видео с джемов или выступлений, чтобы другие импровизаторы могли увидеть вашу игру"
    override val upload: String = "Загрузить"
    override val gender: String = "Пол"
    override val lookingForTeam: String = "Ищу команду"
    override val lookingForTeamDescription: String = "Дайте знать другим импровизаторам,что вы ищете команду"
    override val bio: String = "О себе"
    override val bioPlaceholder: String = "Напишите о себе, чем вы увлекаетесь, какой у вас опыт в импровизации и т.д."
    override val whatImprovDoYouLike: String = "Какая импровизация вам нравится"
    override val yourGoalInImprov: String = "Ваша цель в импровизации"
    override val city: String = "Город"
    override val birthday: String = "Дата рождения"
    override val profile: String = "Профиль"
    override val editProfile: String = "Редактировать профиль"
    override val search: String = "Поиск"
    override val chats: String = "Чаты"
    override val continueString: String = "Продолжить"
    override val back: String = "Назад"
    override val save: String = "Сохранить"
    override val goal: String = "Цель"
    override val improv: String = "Импровизация"
    override val age: String = "Возраст"
    override val withPhoto: String = "С фото"
    override val withVideo: String = "С видео"
    override val reset: String = "Сбросить"
}